### ISSUE TITLE
using N-acetyl cysteine as the substrate

### ISSUE THREAD

**Issue by qxsml** [StructuralGenomicsConsortium/CNP16-iminoquinone-SarsRdRp-mechanstic-study#1]
Hi anyone,

I have a concern about the reaction using free cysteine with the iminoquinone compounds. Below is a reminder of the question:

![the question](https://github.com/StructuralGenomicsConsortium/CNP16-iminoquinone-SarsRdRp-mechanstic-study/assets/147162201/fa07db72-7bae-472d-a28b-86e5263e7cbc)

I feel I should protect the amine group on the free cysteine, just in case.

Below is my thought: 

I assume that the addition of the thiol to the quinone ring is the reaction that happened. Imaging I deliberately synthesised this addition product and obtained its retention time on the HPLC trace. Then I conduct the reaction under the buffer conditions, I should be able to observe this product peak. But what if the free amine also reacted with the ring, as a minor side reaction, I would get a peak that I have to explain what it is.

Also, I suppose cysteine is not the N-terminal of the RdRp protein right? So, its amine is not free. 

I bought **N-acetyl cysteine**, just in case. But hope to consult your opinions. Please let me know what you think.

Thank you very much!
 @mattodd @tmw20653 @ahsgc @RebeckaIsaksson @ahsgc @alvaro-magalhaes @HadiaAmahli

**Comment by tmw20653** [comment]
Xin, check the literature. I am pretty sure these cys capture experiments are typically done with free cysteine and not the protected versions. Tim

**Comment by qxsml** [comment]
Thank you! Yes, I read a paper that used free cysteine with o-quinone to investigate the regiochemistry. Above is my concern, thinking that the amine is also a good nucleophile.

**Comment by tmw20653** [comment]
Try both cyseine and N-Ac cysteine. See if you get a single product. You should be able to tell the difference between SH or NH addition by NMR.

**Comment by mattodd** [comment]
@qxsml see comments coming in re use of glutathione itself as surrogate.
https://twitter.com/MatToddChem/status/1724101005418041575

**Comment by chriswaudby** [comment]
Should be easy to work out by NMR - could even do time-resolved measurements if you want to check the relative reaction rates

**Comment by mattodd** [comment]
@qxsml any updates here to the question of which reagent to use to study the SH capture? Which ones have you now bought/made/used?

**Comment by qxsml** [comment]
After a few trial reactions, N-acetyl cysteine methyl ester was used as the proxy for the reactive SH groups.
