### ISSUE TITLE
Conditions for the cysteine assay

### ISSUE THREAD

**Issue by qxsml** [StructuralGenomicsConsortium/CNP16-iminoquinone-SarsRdRp-mechanstic-study#3]
Plan:

1. Conduct the reactions of RA-0001351 with cysteine under gel-based buffer conditions, using 25 mM Tris-HCl (pH 8), 50 mM NaCl and 10% DMSO, 1.25 mM Mg Chloride, hold 0.01% Triton X-100 and 0.2 mM EDTA. 

The buffer conditions were from Dr Egor Tchesnokov, University of Alberta, who led the test of the gel-based assay on the iminoquinone compounds.

2. Conduct the reactions using RA-0001351 with cysteine under 100 mM sodium phosphate buffer conditions. May also conduct reactions under 100 mM sodium phosphate buffer with 10% DMSO.  
 
The 100 mM sodium phosphate buffer conditions buffer conditions were from a CRO company WuXi AppTec, that performed reactions of GSH with iminoquinone compounds. 

3. Test the other two commercially available iminoquinone compounds under these conditions.

Two iminoquinone compounds have been ordered, 25 mg each:

![Hits purchased](https://github.com/StructuralGenomicsConsortium/CNP16-iminoquinone-SarsRdRp-mechanstic-study/assets/147162201/fae8bba2-0ede-45d4-bfe3-9e3547063fac)

**Comment by mattodd** [comment]
@qxsml I've linked this page to the wiki for the structures of the commercially-available iminiquinones and the possible assay conditions we should be mimicking. Is anything else needed here, or can you close this Issue with a comment?
