### ISSUE TITLE
Attempted monitoring/following the reaction of N-acetyl cysteine with RA-0001351 using NMR.

### ISSUE THREAD

**Issue by qxsml** [StructuralGenomicsConsortium/CNP16-iminoquinone-SarsRdRp-mechanstic-study#4]
I tried to follow the reaction of N-acetyl cysteine with RA-0001351 using NMR.

Solvent choice: a mixture of D2O and DMSO-d6, ideally 10% DMSO-d6 in D2O. 
Reason: the gel-based assay (for testing the iminoquinone) used 10% DMSO in Tris-HCl buffer.

My final attempt: 

1: dissolved 3.6 mg of RA-0001351 in 100 uL of DMSO-d6
2: take aliquots of 5 uL (contains 0.18 mg RA-0001351), diluted with 45 uL DMSO-d6,  then add 50 uL of D2O. The compound crashed out, solution turned cloudy.

Conclusion: 
This result indicates the solubility of RA-0001351 under aqueous conditions is very poor and monitoring the reaction using NMR is unfeasible.

**Comment by mattodd** [comment]
@qxsml I've linked this page to the wiki. Anything else needed? Otherwise please close with a comment.

**Comment by qxsml** [comment]
Thank you!
